# Generated by Django 4.1.3 on 2022-11-26 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0002_candidatemodel_age"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidatemodel",
            name="phone",
            field=models.CharField(default="0000000000", max_length=10),
        ),
    ]
