# Generated by Django 4.1.3 on 2022-11-26 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0006_alter_candidatemodel_age"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidatemodel",
            name="phone",
            field=models.CharField(max_length=10),
        ),
    ]
