# Generated by Django 4.1.3 on 2022-11-27 04:21

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0012_candidatemodel_file_alter_candidatemodel_personality"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidatemodel",
            name="databases",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("MySql", "MySql"),
                    ("Postgres", "Postgres"),
                    ("MongoDB", "MongoDB"),
                    ("SqLite3", "SqLite3"),
                    ("Oracle", "Oracle"),
                    ("Others", "Others"),
                ],
                default="",
                max_length=25,
            ),
        ),
        migrations.AddField(
            model_name="candidatemodel",
            name="frameworks",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("Laravel", "Laravel"),
                    ("Angular", "Angular"),
                    ("Django", "Django"),
                    ("Flask", "Flask"),
                    ("Vue", "Vue"),
                    ("Others", "Others"),
                ],
                default="",
                max_length=25,
            ),
        ),
        migrations.AddField(
            model_name="candidatemodel",
            name="languages",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("Python", "Python"),
                    ("Javascript", "Javascript"),
                    ("Java", "Java"),
                    ("C++", "C++"),
                    ("Ruby", "Ruby"),
                    ("Rust", "Rust"),
                    ("C#", "C#"),
                    ("Others", "Others"),
                ],
                default="",
                max_length=25,
            ),
        ),
        migrations.AddField(
            model_name="candidatemodel",
            name="libraries",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("Ajax", "Ajax"),
                    ("Jquery", "Jquery"),
                    ("React", "React"),
                    ("Chart.js", "Chart.js"),
                    ("Gsap", "Gsap"),
                    ("Others", "Others"),
                ],
                default="",
                max_length=25,
            ),
        ),
        migrations.AddField(
            model_name="candidatemodel",
            name="mobile",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("React native", "React native"),
                    ("Kivy", "Kivy"),
                    ("Flutter", "Flutter"),
                    ("Ionic", "Ionic"),
                    ("Xamarim", "Xamarim"),
                    ("Others", "Others"),
                ],
                default="",
                max_length=25,
            ),
        ),
        migrations.AddField(
            model_name="candidatemodel",
            name="other",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("UML", "UML"),
                    ("SQL", "SQL"),
                    ("Docker", "Docker"),
                    ("Git", "Git"),
                    ("GraphQL", "GraphQL"),
                    ("Others", "Others"),
                ],
                default="",
                max_length=25,
            ),
        ),
    ]
