# Generated by Django 4.1.3 on 2022-11-27 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0013_candidatemodel_databases_candidatemodel_frameworks_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidatemodel",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                ],
                default="Pending",
                max_length=50,
                null=True,
            ),
        ),
    ]
