# Generated by Django 4.1.3 on 2022-11-29 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0014_alter_candidatemodel_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidatemodel",
            name="company_note",
            field=models.TextField(blank=True),
        ),
    ]
